
const translations = {
    en: {
    "auto_page_content_contact_100": "Contact us",
    "auto_page_content_contact_101": "home",
    "auto_page_content_contact_102": "Get in touch",
    "auto_page_content_contact_103": "Contact Our Church For Prayer Support",
    "auto_page_content_contact_104": "We would love to hear from you. Whether you have prayer requests, questions about our services, or want to get involved in our ministries,",
    "auto_page_content_contact_105": "Email Address",
    "auto_page_content_contact_106": "Phone Number",
    "auto_page_content_contact_107": "Our Location",
    "auto_page_content_contact_108": "123 Faith Avenue, Near Peace GardenJubilee Road,",
    "auto_page_content_contact_109": "Share Your Prayer Requests Here",
    "auto_page_content_contact_110": "First Name",
    "auto_page_content_contact_111": "Last Name",
    "auto_page_content_contact_112": "Message",
    "auto_page_content_contact_113": "Send Message",
    "auto_page_content_contact_114": "Where We Locateda",
    "auto_page_content_contact_115": "Find Our Church Location Easily",
    "auto_page_content_contact_116": "Our church is conveniently located in a peaceful and easily accessible area, making it simple for individuals and families to join us for worship, fellowship",

    "auto_page_content_1": "News",
    "auto_page_content_2": "Madhiyas",
    "auto_page_content_3": "The Madhiyas of Shri Panchayati Akhada Shri Niranjani are the foundation of the Akhada's ancient Guru-disciple tradition, spiritual practice, and organizational structure. Each Madhiya, with its unique tradition, dignity, and spiritual identity, significantly contributes to the preservation of Sanatan Dharma, the promotion of the saint tradition, and the propagation of Vedic culture. Presently, there are a total of 18 Madhiyas in the Shri Niranjani Akhada, symbolizing the rich spiritual heritage of the Akhada.",
    "auto_page_content_4": "Rajavat Madhiya",
    "auto_page_content_5": "One of the major traditional Madhiyas of Shri Panchayati Akhada Shri Niranjani.",
    "auto_page_content_6": "This second Madhiya of the Rajavat tradition contributes to advancing the religious and spiritual traditions of the Akhada and strengthening the organization of saints.",
    "auto_page_content_7": "Durganathi Madhiya",
    "auto_page_content_8": "A prestigious Madhiya advancing the Guru-disciple and Sanyas traditions.",
    "auto_page_content_9": "Ramdatti Madhiya",
    "auto_page_content_10": "A traditional Madhiya dedicated to the preservation of Dharma, penance, and spiritual practice.",
    "auto_page_content_11": "Nrisingh Madhiya",
    "auto_page_content_12": "Nrisingh Madhiya represents the ancient ascetic traditions of the Akhada and strengthens the spirit of protecting the Dharma.",
    "auto_page_content_13": "Manmukund Madhiya",
    "auto_page_content_14": "Manmukund Madhiya contributes to spiritual practice, Guru service, and the preservation of the Akhada's cultural heritage.",
    "auto_page_content_15": "Khalsa Madhiya",
    "auto_page_content_16": "Khalsa Madhiya is included among the major Madhiyas maintaining discipline, penance, and the traditional system of the Akhada.",
    "auto_page_content_17": "Brahmanathi Madhiya",
    "auto_page_content_18": "Brahmanathi Madhiya advances the tradition of Vedanta, Guru worship, and the propagation of Sanatan Dharma.",
    "auto_page_content_19": "Gadi Madhiya",
    "auto_page_content_20": "Gadi Madhiya is considered an important traditional Madhiya associated with the religious system and Guru tradition of the Akhada.",
    "auto_page_content_21": "Omkari Madhiya",
    "auto_page_content_22": "Omkari Madhiya represents the ascetic tradition inspired by the spiritual spirit of Lord Shiva's sacred Pranava 'Om'.",
    "auto_page_content_23": "Parmanandi Madhiya",
    "auto_page_content_24": "Parmanandi Madhiya works to develop spiritual progress, self-realization, and the spirit of renunciation among seekers.",
    "auto_page_content_25": "Bodla Madhiya",
    "auto_page_content_26": "Bodla Madhiya is associated with the historical traditions of the Akhada and is considered a prestigious branch of the saint community.",
    "auto_page_content_27": "Multani Madhiya",
    "auto_page_content_28": "Multani Madhiya is an important link in the ancient ascetic tradition, which has advanced the Akhada's tradition in various fields.",
    "auto_page_content_29": "Vaikunthi Madhiya",
    "auto_page_content_30": "Vaikunthi Madhiya is a traditional Madhiya working with the objective of spiritual practice, service, and the preservation of religious rites.",
    "auto_page_content_31": "Sinhasani Madhiya",
    "auto_page_content_32": "Sinhasani Madhiya is one of the prestigious Madhiyas of the Akhada, which strengthens the Shaiva ascetic tradition and religious discipline.",
    "auto_page_content_33": "Dariyav Madhiya",
    "auto_page_content_34": "Dariyav Madhiya preserves the cultural heritage of the Akhada by following the ideals of service, dedication, and the saint tradition.",
    "auto_page_content_35": "Das + Char Madhiya",
    "auto_page_content_36": "Das + Char Madhiya is one of the specific traditional branches of the Akhada, which is an integral part of the Guru-disciple tradition and organizational structure.",
    "auto_page_content_37": "Das + Chhah Madhiya",
    "auto_page_content_38": "Das + Chhah Madhiya is included in the recognized traditional Madhiyas of Shri Panchayati Akhada Shri Niranjani and plays an important role in preserving the spiritual and religious traditions of the Akhada.",
    "auto_page_content_39": "History",
    "auto_page_content_40": "Establishment",
    "auto_page_content_41": "Guru Tradition",
    "auto_page_content_42": "Kumbh Parva",
    "auto_page_content_43": "Naga Sanyasi",
    "auto_page_content_44": "Present Form",
    "auto_page_content_45": "Guru's grace is the light of life",
    "auto_page_content_46": "History of Shri Panchayati Akhada Shri Niranjani",
    "auto_page_content_47": "Establishment and Objective",
    "auto_page_content_48": "The fundamental objective of the Niranjani Akhada is the protection of Dharma, the organization of saints and ascetics, the preservation of Vedic knowledge, and the propagation of Sanatan culture. Ascetics in the Akhada have been imparted education in both scriptures (Shastra) and weapons (Shastra), so they are always ready to protect society and Dharma.",
    "auto_page_content_49": "Guru-Disciple Tradition",
    "auto_page_content_50": "The identity of Niranjani Akhada is its unbroken Guru-disciple tradition. Each ascetic, after receiving initiation from their Guru, progresses on the path of Vedic knowledge, yoga, penance, restraint, and service. This tradition continues to move forward today with the same reverence and discipline.",
    "auto_page_content_51": "Niranjani Akhada in Kumbh Parva",
    "auto_page_content_52": "The Shahi Snan (Royal Bath) of Niranjani Akhada in Mahakumbh and Ardhakumbh is considered highly significant. Millions of devotees gather for the divine darshan of the Naga ascetics and saints of the Akhada. It is not just a religious event but a celebration of the great tradition of Sanatan culture.",
    "auto_page_content_53": "Spiritual Heritage",
    "auto_page_content_54": "Niranjani Akhada works to preserve the invaluable heritage of Vedas, Upanishads, Puranas, Yoga, Meditation, Penance, and Indian spiritual culture. Its ashrams and Madhiyas operate across the country as centers of religion, education, service, and spiritual practice.",
    "auto_page_content_55": "Today, even in the modern era, Shri Panchayati Akhada Shri Niranjani remains active in the works of religion, culture, education, service, and spiritual awakening while keeping its ancient traditions intact. Its branches, Madhiyas, and saint community located nationwide are continuously contributing to the propagation of Sanatan Dharma.",
    "auto_page_content_56": "Key Features of History",
    "auto_page_content_57": "The strength of Niranjani Akhada lies in its unbroken Guru-disciple tradition, where spiritual knowledge, discipline, and ascetic rites are transferred from generation to generation.",
    "auto_page_content_58": "Protection of Dharma",
    "auto_page_content_59": "The primary objective of the Akhada is the preservation of Sanatan Dharma, Vedic culture, and Indian spiritual heritage, as well as religious awakening in society.",
    "auto_page_content_60": "Shri Panchayati Akhada Shri Niranjani is not just an ascetic organization but a vibrant center for the protection of Sanatan Dharma, Vedic tradition, spiritual practice, and national duty. Its traditions are based on the ideals of Guru-disciple relationship, penance, renunciation, service, and protection of Dharma established for centuries.",
    "auto_page_content_61": "Characteristics of Niranjani Akhada",
    "auto_page_content_62": "Shri Panchayati Akhada Shri Niranjani is one of the great spiritual institutions of the Indian Sanatan tradition which has made an invaluable contribution to the preservation of religion, spiritual practice, and culture.",
    "auto_page_content_63": "Dashanami Sanyas Tradition",
    "auto_page_content_64": "Following the principles of the Dashanami Sanyas tradition established by Adi Shankaracharya, the Akhada is the bearer of Vedic knowledge and spiritual discipline.",
    "auto_page_content_65": "The Glorious Tradition of Kumbh",
    "auto_page_content_66": "The royal procession (Shahi Peshwai) and royal bath (Shahi Snan) of Niranjani Akhada in Mahakumbh and Ardhakumbh are symbols of its ancient tradition and spiritual pride.",
    "auto_page_content_67": "॥ Shri Guru Niranjan Dev ॥",
    "auto_page_content_68": "Akhanda Mandalakaram Vyaptam Yena Characharam, Tatpadam Darshitam Yena Tasmai Shri Gurave Namah.",
    "auto_page_content_69": "Agyana Timirandhasya Gyananjana Shalakaya, Chakshurunmilitam Yena Tasmai Shri Gurave Namah.",
    "auto_page_content_70": "Gurur Brahma Gurur Vishnu Gurur Devo Maheshwarah, Guruh Sakshat Parambrahma Tasmai Shri Gurave Namah.",
    "auto_page_content_71": "Guru Tradition of Shri Panchayati Akhada Shri Niranjani",
    "auto_page_content_72": "The Guru tradition is the soul of Indian Sanatan culture. In Shri Panchayati Akhada Shri Niranjani, the Guru is revered as the embodiment of Brahma, Vishnu, and Mahesh. It is the Guru who leads the disciple on the path of self-realization, renunciation, penance, yoga, and religion. This unbroken tradition has been flowing continuously from Guru to disciple for centuries and is alive today with the same reverence, discipline, and dedication.",
    "auto_page_content_73": "Spiritual Knowledge",
    "auto_page_content_74": "The Guru bestows upon the disciple the light of the Vedas, Upanishads, scriptures, and self-realization.",
    "auto_page_content_75": "Sanyas Initiation",
    "auto_page_content_76": "Under the guidance of the Guru, receiving the initiation of Sanyas, the seeker begins a life of religion and spiritual practice.",
    "auto_page_content_77": "Discipline and Spiritual Practice",
    "auto_page_content_78": "The Guru tradition presents the highest ideal of penance, restraint, service, and self-discipline.",

    "new_custom_1": "Roles & Responsibilities",
    "new_custom_2": "Acharya Mahamandaleshwar - Shri Panchayati Akhada Shri Niranjani",
    "new_custom_3": "Niranjan Peethadhishwar",
    "new_custom_4": "Supreme Spiritual Guru - Shri Panchayati Akhada Shri Niranjani",
    "new_custom_5": "Peethadhishwar of Siddhapeeth Shri Dakshin Kali Temple, Haridwar",
    "new_custom_6": "Spiritual Guide of Naga Sanyas Tradition",
    "new_custom_7": "Preacher of Sanatan Dharma and Vedanta",
    "new_custom_8": "Love means service, and service means pleasing God.",
    "new_custom_9": "Secretary - Shri Panchayati Akhada Shri Niranjani",
    "new_custom_10": "President - Mansa Devi Temple Trust, Haridwar",
    "new_custom_11": "Former President of All India Akhada Parishad",
    "new_custom_12": "Chief Patron of Sanatan Dharma and Culture",
    "new_custom_13": "Chief Guide of Religious and Social Works in Haridwar",
    "new_custom_14": "Chief Organizer of Kumbh Mela and Religious Events",
    "new_custom_15": "Service to humanity is service to God. True service is one with no expectation and no selfishness.",

    "auto_key_1": "home page",
    "auto_key_2": "our\n                                        about",
    "auto_key_3": "History",
    "auto_key_4": "Guru\n                                        tradition",
    "auto_key_5": "madhiyas",
    "auto_key_6": "saint and\n                                        Mahant",
    "auto_key_7": "Mahamandaleshwar",
    "auto_key_8": "Mahant",
    "auto_key_9": "Sermons",
    "auto_key_10": "Sermon\n                                                Details",
    "auto_key_11": "Our\n                                                Ministries",
    "auto_key_12": "Ministry\n                                                Details",
    "auto_key_13": "Pastor",
    "auto_key_14": "Pastor\n                                                Details",
    "auto_key_15": "Testimonials",
    "auto_key_16": "Image\n                                                Gallery",
    "auto_key_17": "Video\n                                                Gallery",
    "auto_key_18": "FAQs",
    "auto_key_19": "404",
    "auto_key_20": "the arena\n                                        branches of",
    "auto_key_21": "nationwide\n                                                branches",
    "auto_key_22": "of the arena\n                                                branches",
    "auto_key_23": "our\n                                                branches",
    "auto_key_24": "branch center",
    "auto_key_25": "activities",
    "auto_key_26": "Program",
    "auto_key_27": "Kumbh Mela",
    "auto_key_28": "diorama",
    "auto_key_29": "news",
    "auto_key_30": "Donation",
    "auto_key_31": "Contact",
    "auto_key_32": "॥ Om Guru Niranjan Devay\n                                Namah ॥",
    "auto_key_33": "Panchayati Akhara\n                                Shri Niranjani",
    "auto_key_34": "our\n                                about",
    "auto_key_35": "History\n                                know",
    "auto_key_36": "Inspired by the great Dashnami tradition of Adi Shankaracharya, Panchayati Akhara\n                                Shri Niranjani has been protecting Sanatan Dharma, spreading spiritual consciousness and preserving the saint tradition for centuries.\n                                Dedicated to conservation and human welfare.",
    "auto_key_37": "centuries of spiritual tradition",
    "auto_key_38": "large group of volunteers",
    "auto_key_39": "Sanatan Dharma Service and Protection",
    "auto_key_40": "Our story, faith,\n                                Mission and Vision",
    "auto_key_41": "Panchayati Akhara Shri\n                                Dashnami sect founded by Niranjani, the great philosopher and religious pioneer Adi Shankaracharya\n                                It is a very ancient, stunning and prestigious branch. This Akhara was established in Vikram Samvat.\n                                It took place in 1429 (AD 1472).",
    "auto_key_42": "guru tradition",
    "auto_key_43": "Dashanami Sannyasa established by Adi Guru Shankaracharya\n                                        Preservation and promotion of tradition.",
    "auto_key_44": "Religion and social service",
    "auto_key_45": "Propagation of Sanatan Dharma, spiritual awakening and public welfare\n                                        Continuously dedicated to.",
    "auto_key_46": "learn more",
    "auto_key_47": "Shri Mahant Ravindrapuri Maharaj",
    "auto_key_48": "Secretary – Panchayati Akhara Shri Niranjani President – ​​Mansa Devi Temple Trust",
    "auto_key_49": "॥ Om Namah Shivay.",
    "auto_key_50": "॥ Om Guru Niranjan Dev Namah ॥",
    "auto_key_51": "our traditions",
    "auto_key_52": "our religious\n                            Traditions and rituals",
    "auto_key_53": "Guru\n                                                    tradition",
    "auto_key_54": "Following the Dashnami tradition of Adi Guru Shankaracharya\n                                                While preserving and promoting the Guru-Shishya tradition.",
    "auto_key_55": "Leam more",
    "auto_key_56": "Sanatan Dharma\n                                                    service",
    "auto_key_57": "Preservation of Sanatan Dharma, spiritual awakening and society\n                                                Continuously dedicated to service.",
    "auto_key_58": "Aquarius and\n                                                    religious event",
    "auto_key_59": "Kumbh Mela, Shahi Snan and other religious events\n                                                Glorious participation of the Akhara in.",
    "auto_key_60": "preaching religion\n                                                    and promotion",
    "auto_key_61": "Propagation of Sanatan culture, lecture series\n                                                And religious education programs.",
    "auto_key_62": "our purpose",
    "auto_key_63": "shri guru\n                                Niranjan Dev and Dashnami Sannyasa Tradition",
    "auto_key_64": "Sri Guru Niranjan Dev\n                                Shri Panchayati Akhara established in the sacred tradition of Shri Niranjani, Sanatan Vedic tradition and\n                                Dashnami follows the Sannyasa tradition. In this tradition the guru-disciple relationship is spiritual.\n                                Sadhana and protection of religion have the highest place.",
    "auto_key_65": "Shri 1008 Shri Acharya Mahamandaleshwar Swami Shri Kailashananda\n                                    Giriji Maharaj",
    "auto_key_66": "current acharya guru",
    "auto_key_67": "Learn Guru Tradition",
    "auto_key_68": "shri guru\n                                                    Niranjan Dev Stuti",
    "auto_key_69": "Niranjan Dev through praise and Guru tradition\n                                                The path of spiritual practice and devotion to the Guru.",
    "auto_key_70": "Leam more",
    "auto_key_71": "Dashnami Sannyasa which has been going on since Adi Guru Shankaracharya\n                                                Tradition and glorious tradition of present Acharya Guru.",
    "auto_key_72": "Aquarius\n                                                    festival",
    "auto_key_73": "Haridwar, Prayag, Ujjain and Nashik Kumbh festival\n                                                Spiritual importance and glorious tradition of Akhara.",
    "auto_key_74": "Madhias and\n                                                    branches",
    "auto_key_75": "18 Madhis of Shri Panchayati Niranjani Akhara and\n                                                Spiritual centers established across India.",
    "auto_key_76": "major legacy",
    "auto_key_77": "Panchayati Akhara Shri\n                            Spiritual and religious heritage of Niranjani",
    "auto_key_78": "seven\n                                        the arena",
    "auto_key_79": "Seven of Shaiva Sanyasi tradition\n                                            Shri Panch Niranjani Akhara has a special place among the major Akharas.",
    "auto_key_80": "Read More",
    "auto_key_81": "18\n                                        madhiyas",
    "auto_key_82": "Eighteen established across the country\n                                            Madhis are major centers of spiritual practice and tradition.",
    "auto_key_83": "four\n                                        Mahavakya",
    "auto_key_84": "Aham Brahmasmi •\n                                            Ayamatma Brahma • Tattvamasi • Prajnanam Brahma",
    "auto_key_85": "From Guru tradition to Kumbh festival, Panchayati Akhara of Shri Niranjani\n                            Explore spiritual heritage",
    "auto_key_86": "View all topics →",
    "auto_key_87": "“The Most Revered Shri 1008 Shri Acharya Mahamandaleshwar Swami Shri\n                                    Kailashanand Giri ji\n                                    Maharaj”",
    "auto_key_88": "know",
    "auto_key_89": "Acharya Sandesh",
    "auto_key_90": "most respected shri\n                                1008 Shri Acharya\n                                Mahamandaleshwar Swami Shri Kailashanand Giri Ji Maharaj",
    "auto_key_91": "Acharya Guru's\n                                Jeevan Sanatan Dharma,\n                                It is a symbol of complete dedication towards Guru-disciple tradition and spiritual practice. their\n                                Shri Panchayati Akhara under the guidance of Shri Niranjani based on its ancient traditions, spiritual\n                                It is continuously taking forward the resolution of preserving values and religion.",
    "auto_key_92": "Post:",
    "auto_key_93": "Acharya Mahamandaleshwar",
    "auto_key_94": "legacy:",
    "auto_key_95": "Dashanami Sannyasa Tradition",
    "auto_key_96": "read message",
    "auto_key_97": "eternal knowledge\n                            and spiritual tradition",
    "auto_key_98": "twelfth\n                                                        Jyotirlinga",
    "auto_key_99": "Twelve Jyotirlingas dedicated to Lord Shiva India\n                                                    Are the centers of spiritual consciousness.",
    "auto_key_100": "Saptamokshadayika Puri",
    "auto_key_101": "Ayodhya, Mathura, Maya, Kashi, Kanchi, Avantika\n                                                    And religious importance of Dwarka.",
    "auto_key_102": "Panchkanya",
    "auto_key_103": "Ahalya, Draupadi, Sita, Tara and Mandodari\n                                                    Importance of remembrance.",
    "auto_key_104": "Spiritual heritage and eternal traditions of Shri Panchayati Niranjani Akhara\n                            observe the",
    "auto_key_105": "View all sections",
    "auto_key_106": "Shri Mahant\n                                Ravindrapuri Maharaj",
    "auto_key_107": "Secretary – Panchayati\n                                Akhara Shri Niranjani President – Mansa Devi Temple Trust, Haridwar",
    "auto_key_108": "Shri Mahant Ravindrapuri\n                                Maharaj, Secretary of Panchayati Akhara Shri Niranjani\n                                And is the President of Mansa Devi Temple Trust, Haridwar. Guru tradition, preservation of Sanatan Dharma\n                                And he has an important contribution in the promotion of spiritual traditions. under his guidance\n                                The Akhara aims to carry forward its ancient traditions, religious events and spiritual values.\n                                Is continuously working for.",
    "auto_key_109": "and\n                                know",
    "auto_key_110": "Akhara Seven",
    "auto_key_111": "dashanami sannyasa\n                                seven heads of tradition\n                                the arena",
    "auto_key_112": "India's prosperity\n                                In spiritual tradition, Dashanami\n                                Sanyas Akharas play an important role. These Akharas have been eternal for thousands of years.\n                                Preservation and promotion of religious values, philosophies and traditions.",
    "auto_key_113": "View All\n                                Stories",
    "auto_key_114": "“Shri Panch Niranjani Akhara”",
    "auto_key_115": "Head of Dashanami Shaiva Sannyasa tradition and\n                                                        Of the prestigious arenas\n                                                        One. This Akhara is based on Guru-disciple tradition, Vedic knowledge, penance, meditation and\n                                                        Dedicated to the preservation of Sanatan Dharma. Its in Kumbh festival\n                                                        There is a special role and a glorious tradition of royal bath.",
    "auto_key_116": "“Shri Panch Juna Akhara”",
    "auto_key_117": "An icon of the Shaiva Sanyasi tradition\n                                                        The arena, which is sadhana,\n                                                        Dedicated to the service of Guru-tradition and Sanatan Dharma. its\n                                                        Saints active in propagating spiritual life and Vedic values\n                                                        Live.",
    "auto_key_118": "“Shri Panch Anand Akhara”",
    "auto_key_119": "Spiritual Discipline, Vairagya and Vedanta\n                                                        Dashnami tradition based on\n                                                        Important arena. Sadhana, Sannyasa and religious propagation are its main\n                                                        Features are.",
    "auto_key_120": "“Shri Panch Avahan Akhara”",
    "auto_key_121": "Worship of Lord Shiva and Dashnami Sannyasa\n                                                        to preserve tradition\n                                                        Dedicated arena. Spiritual practice, Vedic studies and religious\n                                                        It has a special place in following traditions.",
    "auto_key_122": "“Shri Panch Atal Akhara”",
    "auto_key_123": "Strong spiritual discipline, penance and\n                                                        Sannyasi ideals of life\n                                                        Major Shaivite Akhara following. This religion, culture and Vedic\n                                                        Contributes to the preservation of traditions.",
    "auto_key_124": "“Shri Panch Nirvani Akhara”",
    "auto_key_125": "“Shri Panch Agni Akhara”",
    "auto_key_126": "Vedic sacrifice, penance, celibacy and\n                                                        from the tradition of spiritual practice\n                                                        Dashnami Akhara connected. This special emphasis on sacrifice, discipline and knowledge\n                                                        Gives.",
    "auto_key_127": "Shaiva Akhara",
    "auto_key_128": "Vaishnav Akhara",
    "auto_key_129": "nostalgic arena",
    "auto_key_130": "Nirmal Akhara",
    "auto_key_131": "13",
    "auto_key_132": "total recognized akharas",
    "auto_key_133": "/5",
    "auto_key_134": "4.9",
    "auto_key_135": "Based on 2500+ reviews",
    "auto_key_136": "Frequently Asked\n                                Questions",
    "auto_key_137": "Answers to the\n                                question you might have about",
    "auto_key_138": "Q1. Shri Panchayati Niranjani Akhara is included in which Akharas?",
    "auto_key_139": "1) Shri Panch Niranjani Akhara 2) Shri Panch Anand Akhara 3) Shri Panch Avahan Akhara 4) Shri Panch Atal Akhara 5) Shri Panch Nirvani Akhara 6) Shri Panch Agni Akhara 7) Shri Panch Juna Akhara.",
    "auto_key_140": "Q2. How many Madhis are there in Shri Panchayati Niranjani Akhara?",
    "auto_key_141": "18 Madhi under Shri Panchayati Niranjani Akhara\n                                            Are.",
    "auto_key_142": "Q3. What are the four Mahavakyas of the Akhara?",
    "auto_key_143": "1) Aham Brahmasmi 2) Ayamatma Brahma 3) Tattvamasi 4) Prajnanam Brahma",
    "auto_key_144": "Q4. At which places is the Kumbh festival organized?",
    "auto_key_145": "Kumbh festival is organized at four places – 1) Haridwar 2) Prayag 3) Ujjain 4) Nashik",
    "auto_key_146": "Q5. Who is the present Acharya Guru?",
    "auto_key_147": "Paramahamsa Parivrajakacharya Shrimad Brahmanishtha Pujyapad\n                                            Shri Niranjan Peethadheeshwar Shri Shri 1008 Acharya Mahamandaleshwar Swami Shri\n                                            Kailashanand Giri Ji Maharaj.",
    "auto_key_148": "॥ Sri Guru Niranjan Dev\n                                Praise ॥",
    "auto_key_149": "Omkarabindu\n                                Sanyutam Nityam Dhyayanti Yoginah. Kamadam Mokshadam Chaiva Omkaraya Namo",
    "auto_key_150": "Namah॥",
    "auto_key_151": "Shri Guru Niranjan Dev Praise-",
    "auto_key_152": "special information",
    "auto_key_153": "of Niranjani tradition\n                            special spiritual heritage",
    "auto_key_154": "Dashanami Sannyasa tradition established by Adi Shankaracharya Indian\n                                    Spiritual life, Vedic knowledge and asceticism are the cornerstone of religion.",
    "auto_key_155": "Learn more",
    "auto_key_156": "History of Akharas",
    "auto_key_157": "Establishment of Akharas in Indian saint tradition for protection of religion,\n                                    It was done for the purpose of spiritual practice and preservation of Vedic culture.",
    "auto_key_158": "guru-disciple tradition",
    "auto_key_159": "The tradition of knowledge, penance, renunciation and religion continues from Guru to disciple.\n                                    It has been flowing, which is the basic identity of the Akhara.",
    "auto_key_160": "Shri Panchayati Niranjani Akhara",
    "auto_key_161": "etc\n                                A major Akhara of Dashnami Shaiva Sannyasa tradition established by Shankaracharya, which is based on Sanatan Dharma,\n                                Dedicated to preserving Guru-Shishya tradition and spiritual culture.",
    "auto_key_162": "Stay connected to Sanatan tradition",
    "auto_key_163": "॥ Om Guru Niranjan Devaya Namah ॥",
    "auto_key_164": "Quick Links",
    "auto_key_165": "home page",
    "auto_key_166": "about us",
    "auto_key_167": "branches",
    "auto_key_168": "kumbh festival",
    "auto_key_169": "Our Services",
    "auto_key_170": "Sri Guru Niranjan Dev\n                                        praise",
    "auto_key_171": "four great sentences",
    "auto_key_172": "Sapt Mokshadayini Puris",
    "auto_key_173": "Dwadash Jyotirlinga",
    "auto_key_174": "Gurukartikeya Stotra",
    "auto_key_175": "Sapta Chiranjeevi Mantra",
    "auto_key_176": "📍 Ganeshghat, Mayapur, Haridwar, Uttarakhand 📍 Prayagraj (Uttar Pradesh) 📍 Kashi / Varanasi (Uttar Pradesh) 📍 Ujjain (Madhya Pradesh) 📍 Trimbakeshwar, Nashik (Maharashtra)",
    "auto_key_177": "Copyright © 2026 Panchayati Akhara Shri Niranjani. All Rights Reserved.\n                                Digital Experience by",
    "auto_key_178": "ATHInnovations.",
    "auto_key_179": "Sanatan Dharma, Guru-disciple tradition and\n                                Glorious heritage of spiritual practice",
    "auto_key_180": "Shri Panchayati Niranjani Akhara Dashnami Shaiva Sannyasa\n                                It is one of the main and ancient Akharas of the tradition. Established by Adi Shankaracharya this great\n                                The purpose of the tradition is to preserve Sanatan Dharma, spread Vedic knowledge, and maintain the Guru-Shishya tradition.\n                                To promote and create spiritual awakening in the society. For centuries this Akhara has been a place of penance, sacrifice, service and\n                                Guides Indian spiritual culture by following the ideals of protecting Dharma.\n                                Has been.",
    "auto_key_181": "Mission",
    "auto_key_182": "Preservation of Sanatan Dharma, promotion of Vedic traditions, strengthening of Guru-shishya tradition.\n                                        To do and spread spiritual consciousness, service and values in the society.",
    "auto_key_183": "our vision",
    "auto_key_184": "Building a society where through religion, culture, spirituality and human values\n                                        The generations to come should remain connected to the Sanatan tradition and work towards the welfare of the nation and humanity.\n                                        Contribute to.",
    "auto_key_185": "learn history",
    "auto_key_186": "Shrimahant Ravindra Puri Ji Maharaj",
    "auto_key_187": "President, Shri Panchayati Niranjani Akhara",
    "auto_key_188": "Shree Panchayati\n                                Akhara Shri Niranjani is a prestigious and spiritual Akhara of Dashnami Sannyasa tradition, which\n                                Dedicated to Sanatan Vedic culture, Guru-disciple tradition and the great objective of protecting Dharma.\n                                Is. The Akhara glorifies the worship of Lord Shiva, Vedic knowledge, penance, renunciation and ascetic life.\n                                Spreads spiritual consciousness in the society by following the tradition.",
    "auto_key_189": "this holy\n                                In tradition, the position of Guru is considered supreme. Guru-devotion, Vedanta philosophy, four in the Akhara\n                                Mahavakya, Dwadash Jyotirlinga, Sapta Mokshadayini Puris and basic principles of Sanatan Dharma\n                                Study, conservation and promotion is done continuously.",
    "auto_key_190": "Shri Panchayati Akhara Shri Niranjani is one of the seven major Akharas of India. its tradition\n                                    Sanatan through major pilgrimage sites, temples and religious centers across the country\n                                    Works to strengthen culture. Akhara especially during Kumbh, Ardh Kumbh and\n                                    Plays an active role in great religious events like Simhastha and the royal bath.\n                                    Carries out ancient tradition.",
    "auto_key_191": "of the arena\n                                The center of spiritual practice is devotion to the Guru, penance, restraint, service and enlightenment. its purpose\n                                Not only the preservation of the Sannyasa tradition, but also the importance of promoting religion, morality, national service and\n                                It is also to establish the values of human welfare. Saints and Mahatmas associated with the Akhara dedicated their lives to\n                                Dedicated to public welfare and propagation of Sanatan Dharma.",
    "auto_key_192": "penance • renunciation\n                                • Service • Sadhana • Protection of Dharma • Devotion to Guru",
    "auto_key_193": "Shree Panchayati\n                                The tradition of Akhara Shri Niranjani is of complete dedication to the Guru, study of scriptures and sadhana.\n                                It is based on continuous efforts towards purity and self-realization. Considering Guru as Brahmaswarupa\n                                Following his teachings is considered to be the basic basis of the spiritual life of a seeker. the arena\n                                Guru-shishya tradition is not only about exchange of knowledge but also in every sphere of life.\n                                It is a medium of values, discipline and spiritual progress.",
    "auto_key_194": "Preservation of Sanatan Dharma and Vedic culture.",
    "auto_key_195": "Promotion of Guru-Shishya tradition.",
    "auto_key_196": "To strengthen the spirit of penance, sacrifice and spiritual practice.",
    "auto_key_197": "Propagation of Vedanta and spiritual knowledge.",
    "auto_key_198": "To promote religion, service and public welfare works.",
    "auto_key_199": "To safely transmit Indian spiritual heritage to future generations.",
    "auto_key_200": "Our Core Principles",
    "auto_key_201": "Panchayati Akhara Shri Niranjani's Spiritual\n                            principle",
    "auto_key_202": "guru-disciple tradition",
    "auto_key_203": "Self-realization through Guru's teachings, blessings and knowledge considering him as Brahman.\n                                    And moving forward on the path of salvation is our highest tradition.",
    "auto_key_204": "Vedanta and four Mahavakyata",
    "auto_key_205": "The Akhara follows the tradition of Advaita Vedanta. Four Mahavakyas of soul and Brahma\n                                    Gives the message of unity and inspires the seeker towards self-knowledge.",
    "auto_key_206": "Penance, renunciation and meditation",
    "auto_key_207": "Self-purification and public welfare through restraint, penance, renunciation, service and devotion to Shiva.\n                                    The path itself is the basic foundation of a monk's life.",
    "auto_key_208": "Know our spiritual principles based on Sanatan Dharma, Guru-Bhakti and Vedanta -",
    "auto_key_209": "View all principles",
    "auto_key_210": "spiritual heritage",
    "auto_key_211": "Priceless spiritual heritage of Niranjani Akhara",
    "auto_key_212": "Shri Panchayati Akhara Shri Niranjani is not just an ascetic tradition but a living spiritual heritage of Sanatan Dharma. Its spiritual practice, scriptures, Guru tradition and the spirit of protection of religion inspire millions of devotees even today.",
    "auto_key_213": "classical tradition",
    "auto_key_214": "Study, preservation and propagation of Vedas, Upanishads, Char Mahavakyas, Stotras and Vedic knowledge are included in the major spiritual traditions of the Akhara.",
    "auto_key_215": "Pilgrimage and spiritual center",
    "auto_key_216": "Madhis located at many holy places including Haridwar, Prayagraj, Kashi, Ujjain, Trimbakeshwar are major centers of spiritual practice, service and saint tradition.",
    "auto_key_217": "Learn spiritual heritage",
    "auto_key_218": "our leadership",
    "auto_key_219": "Present spiritual leadership of Panchayati Akhara Shri Niranjani",
    "auto_key_220": "Most Revered Sri Sri 1008 Acharya Mahamandaleshwar Niranjan Peethadhishwar Swami Kailashanand Giri Ji Maharaj",
    "auto_key_221": "chairman",
    "auto_key_222": "Mahant Omkar Giri Ji Maharaj",
    "auto_key_223": "Secretary",
    "auto_key_224": "Taking forward the unbroken tradition of Sanatan Dharma under the guidance of saints, Shri Panchayati Akhara Shri Niranjani is continuously dedicated to the service of the nation, religion and culture.",
    "auto_key_225": "Features of the arena",
    "auto_key_226": "Proud center of protection of Sanatan Dharma, Sadhu tradition and spiritual leadership",
    "auto_key_227": "Shri Panchayati Akhara is the main Akhara of Shri Niranjani Dashnami Shaiv ​​Sannyasa tradition. It was established with the aim of protecting religion, culture, Vedas, Sanyas tradition and nationalism. Even today this Akhara is playing a leading role in spiritual practice, Guru-disciple tradition and preservation of Sanatan culture.",
    "auto_key_228": "E.",
    "auto_key_229": "108",
    "auto_key_230": "year of establishment",
    "auto_key_231": "A major Akhara among Dashnami Shaiva Akharas.",
    "auto_key_232": "A glorious part of Adi Shankaracharya's Dashnami Sannyasa tradition.",
    "auto_key_233": "Dedicated to the preservation of Vedas, Shastras, penance, yoga and Sanatan culture.",
    "auto_key_234": "Know the history of the Akhara",
    "auto_key_235": "message of tradition",
    "auto_key_236": "Shri Panchayati Akhara Shri Niranjani – Immortal symbol of Sanatan Sadhana",
    "auto_key_237": "Shri Panchayati Akhara Shri Niranjani is not just an Akhara, but a living center of Sanatan Dharma, Veda-Vedanta, penance, renunciation and Guru-disciple tradition. It was established with the objective of protecting religion, organization of saint society and spreading spiritual consciousness. Even today the Akhara is continuously dedicated to the service of the nation, culture and humanity.",
    "auto_key_238": "Know about the arena",
    "auto_key_239": "Our main centers",
    "auto_key_240": "Major seats and centers of Panchayati Akhara Shri Niranjani",
    "auto_key_241": "The spiritual and administrative activities of Shri Panchayati Akhara Shri Niranjani are conducted in the major pilgrimage areas of India. These centers are the main basis for the protection of saints, devotees and Sanatan tradition.",
    "auto_key_242": "View all centers",
    "auto_key_243": "“Haridwar (Main Bench)”",
    "auto_key_244": "📍 Ganesh Ghat, Mayapur, Haridwar, Uttarakhand",
    "auto_key_245": "The headquarters and main administrative center of Shri Panchayati Akhara Shri Niranjani.",
    "auto_key_246": "“Prayagraj”",
    "auto_key_247": "📍 Daraganj, Prayagraj, Uttar Pradesh",
    "auto_key_248": "Center of major activities of the Akhara during Mahakumbh and Magh Mela.",
    "auto_key_249": "ujjain",
    "auto_key_250": "📍 Ujjain, Madhya Pradesh",
    "auto_key_251": "Main center of Akhara in Simhastha Mahaparva and Shahi Snan.",
    "auto_key_252": "Trimbakeshwar, Nashik",
    "auto_key_253": "📍 Nashik, Maharashtra",
    "auto_key_254": "Major religious center associated with Kumbh festival and Dashnami Sannyasa tradition.",
    "auto_key_255": "major spiritual center",
    "auto_key_256": "904",
    "auto_key_257": "Establishment",
    "auto_key_258": "Kumbh Nagri",
    "auto_key_259": "Prominent in Dashnami Shaiva Akharas",
    "auto_key_260": "+ year",
    "auto_key_261": "1100",
    "auto_key_262": "glorious tradition",
    "history_1": "History",
    "history_2": "The Glorious Tradition of Shri Panchayati Akhada Shri Niranjani",
    "history_3": "Establishment",
    "history_4": "Guru Tradition",
    "history_5": "Madhiyas",
    "history_6": "Kumbh Parv",
    "history_7": "Naga Sanyasis",
    "history_8": "Present Form",
    "history_9": "Guru's grace is the light of life",
    "history_10": "History of Shri Panchayati Akhada Shri Niranjani",
    "history_11": "Shri Panchayati Akhada Shri Niranjani is one of the prominent and ancient Akhadas of the Dashanami Sanyas tradition. It was established with the objective of protecting Sanatan Dharma, propagating Vedas and Shastras, preserving the Sanyas tradition, and spreading spiritual consciousness in society. This Akhada is considered an important part of the Dashanami tradition established by Adi Shankaracharya. <br><br>\n                                For centuries, Niranjani Akhada has been a center of Dharma, penance, yoga, sacrifice, and the Guru-disciple tradition. Its glorious presence in Mahakumbh, Ardhakumbh, and other religious events is a living identity of Sanatan culture.",
    "history_12": "Establishment and Objectives",
    "history_13": "The main objective of Niranjani Akhada is the protection of Dharma, organization of saints and sages, preservation of Vedic knowledge, and propagation of Sanatan culture. Sanyasis in the Akhada have been imparted education in both Shastras (scriptures) and Shastras (weapons), so that they are always ready to protect society and Dharma.",
    "history_14": "Guru-Disciple Tradition",
    "history_15": "The identity of Niranjani Akhada is its unbroken Guru-disciple tradition. Every Sanyasi, after receiving initiation from his Guru, progresses on the path of Vedic knowledge, yoga, penance, restraint, and service. This tradition continues to move forward with the same reverence and discipline today.",
    "history_16": "Niranjani Akhada in Kumbh Parv",
    "history_17": "The Shahi Snan of Niranjani Akhada in Mahakumbh and Ardhakumbh is considered extremely important. Millions of devotees attend to have the divine darshan of the Naga Sanyasis and saints of the Akhada. It is not just a religious event but a celebration of the great tradition of Sanatan culture.",
    "history_18": "Spiritual Heritage",
    "history_19": "Niranjani Akhada works to preserve the invaluable heritage of Vedas, Upanishads, Puranas, Yoga, meditation, penance, and Indian spiritual culture. Its ashrams and Madhiyas function as centers of Dharma, education, service, and spiritual practice across the country.",
    "history_20": "Today, Shri Panchayati Akhada Shri Niranjani is active in the works of Dharma, culture, education, service, and spiritual awakening while keeping its ancient traditions intact even in the modern age. Its branches, Madhiyas, and saint society located across the country are continuously contributing to the propagation of Sanatan Dharma.",
    "history_21": "Key Features of History",
    "history_22": "The strength of Niranjani Akhada lies in its unbroken Guru-disciple tradition, where spiritual knowledge, discipline, and Sanyas rites are transferred from generation to generation.",
    "history_23": "Protection of Dharma",
    "history_24": "The main objective of the Akhada is the protection of Sanatan Dharma, Vedic culture, and Indian spiritual heritage, and awakening Dharma in society.",
    "history_25": "Shri Panchayati Akhada Shri Niranjani is not just a Sanyasi organization, but a living center for the protection of Sanatan Dharma, Vedic tradition, spiritual practice, and national duty. Its traditions have been based on the ideals of Guru-disciple relationship, penance, sacrifice, service, and protection of Dharma for centuries.",
    "history_26": "Features of Niranjani Akhada",
    "history_27": "Shri Panchayati Akhada Shri Niranjani is one of those great spiritual institutions of the Indian Sanatan tradition that has made an invaluable contribution to the preservation of Dharma, spiritual practice, and culture.",
    "history_28": "Dashanami Sanyas Tradition",
    "history_29": "Following the principles of the Dashanami Sanyas tradition established by Adi Shankaracharya, the Akhada is a carrier of Vedic knowledge and spiritual discipline.",
    "history_30": "Glorious Tradition of Kumbh",
    "history_31": "The Shahi Peshwai and Shahi Snan of Niranjani Akhada in Mahakumbh and Ardhakumbh are symbols of its ancient tradition and spiritual glory."
},
    hi: {
    "auto_page_content_contact_100": "संपर्क करें",
    "auto_page_content_contact_101": "मुख्य पृष्ठ",
    "auto_page_content_contact_102": "संपर्क में रहें",
    "auto_page_content_contact_103": "श्री निरंजनी अखाड़े से संपर्क करें",
    "auto_page_content_contact_104": "अखाड़े से संबंधित किसी भी जानकारी, धार्मिक आयोजनों अथवा अन्य आध्यात्मिक कार्यों के लिए आप हमसे संपर्क कर सकते हैं।",
    "auto_page_content_contact_105": "ईमेल आईडी",
    "auto_page_content_contact_106": "फ़ोन नंबर",
    "auto_page_content_contact_107": "हमारा पता",
    "auto_page_content_contact_108": "श्री पंचायती अखाड़ा निरंजनी, दारागंज, प्रयागराज",
    "auto_page_content_contact_109": "अपना संदेश हमें भेजें",
    "auto_page_content_contact_110": "पहला नाम",
    "auto_page_content_contact_111": "अंतिम नाम",
    "auto_page_content_contact_112": "संदेश",
    "auto_page_content_contact_113": "संदेश भेजें",
    "auto_page_content_contact_114": "हमारा स्थान",
    "auto_page_content_contact_115": "आसानी से हमारा अखाड़ा खोजें",
    "auto_page_content_contact_116": "हमारा अखाड़ा एक शांतिपूर्ण और सुलभ क्षेत्र में स्थित है, जहाँ आकर आप आध्यात्मिक शांति और संत समागम का लाभ उठा सकते हैं।",

    "auto_page_content_1": "समाचार",
    "auto_page_content_2": "मढ़ियाँ",
    "auto_page_content_3": "श्री पंचायती अखाड़ा श्री निरंजनी की मढ़ियाँ अखाड़े की प्राचीन गुरु-शिष्य परंपरा, आध्यात्मिक साधना तथा संगठनात्मक व्यवस्था की आधारशिला हैं। प्रत्येक मढ़ी अपनी विशिष्ट परंपरा, मर्यादा एवं आध्यात्मिक पहचान के साथ सनातन धर्म के संरक्षण, संत परंपरा के संवर्धन तथा वैदिक संस्कृति के प्रचार-प्रसार में महत्वपूर्ण योगदान देती है। वर्तमान में श्री निरंजनी अखाड़े में कुल 18 मढ़ियाँ विद्यमान हैं, जो अखाड़े की समृद्ध आध्यात्मिक विरासत का प्रतीक हैं.",
    "auto_page_content_4": "राजावत मढ़ी",
    "auto_page_content_5": "श्री पंचायती अखाड़ा श्री निरंजनी की प्रमुख परंपरागत मढ़ियों में से एक।",
    "auto_page_content_6": "राजावत परंपरा की यह दूसरी मढ़ी अखाड़े की धार्मिक एवं आध्यात्मिक परंपराओं को आगे बढ़ाने तथा संतों के संगठन को सुदृढ़ बनाने में योगदान देती है।",
    "auto_page_content_7": "दुर्गानाथी मढ़ी",
    "auto_page_content_8": "गुरु-शिष्य परंपरा एवं संन्यास परंपरा को आगे बढ़ाने वाली प्रतिष्ठित मढ़ी।",
    "auto_page_content_9": "रामदत्ती मढ़ी",
    "auto_page_content_10": "धर्म, तप एवं साधना के संरक्षण हेतु समर्पित परंपरागत मढ़ी।",
    "auto_page_content_11": "नृसिंह मढ़ी",
    "auto_page_content_12": "नृसिंह मढ़ी अखाड़े की प्राचीन संन्यासी परंपराओं का प्रतिनिधित्व करती है और धर्मरक्षा की भावना को सुदृढ़ करती है।",
    "auto_page_content_13": "मनमुकुन्द मढ़ी",
    "auto_page_content_14": "मनमुकुन्द मढ़ी आध्यात्मिक साधना, गुरु सेवा तथा अखाड़े की सांस्कृतिक विरासत के संरक्षण में अपना योगदान देती है।",
    "auto_page_content_15": "खालसा मढ़ी",
    "auto_page_content_16": "खालसा मढ़ी अनुशासन, तप एवं अखाड़े की पारंपरिक व्यवस्था को बनाए रखने वाली प्रमुख मढ़ियों में सम्मिलित है।",
    "auto_page_content_17": "ब्रह्मनाथी मढ़ी",
    "auto_page_content_18": "ब्रह्मनाथी मढ़ी वेदांत, गुरु उपासना एवं सनातन धर्म के प्रचार-प्रसार की परंपरा को आगे बढ़ाती है।",
    "auto_page_content_19": "गादी मढ़ी",
    "auto_page_content_20": "गादी मढ़ी अखाड़े की धार्मिक व्यवस्था एवं गुरु परंपरा से जुड़ी महत्वपूर्ण परंपरागत मढ़ी मानी जाती है।",
    "auto_page_content_21": "ॐकारी मढ़ी",
    "auto_page_content_22": "ॐकारी मढ़ी भगवान शिव के पवित्र प्रणव ‘ॐ’ की आध्यात्मिक भावना से प्रेरित संन्यास परंपरा का प्रतिनिधित्व करती है।",
    "auto_page_content_23": "परमानन्दी मढ़ी",
    "auto_page_content_24": "परमानन्दी मढ़ी साधकों में आध्यात्मिक उन्नति, आत्मज्ञान एवं वैराग्य की भावना को विकसित करने का कार्य करती है।",
    "auto_page_content_25": "बोडला मढ़ी",
    "auto_page_content_26": "बोडला मढ़ी अखाड़े की ऐतिहासिक परंपराओं से जुड़ी हुई है तथा संत समाज की एक प्रतिष्ठित शाखा मानी जाती है।",
    "auto_page_content_27": "मुल्तानी मढ़ी",
    "auto_page_content_28": "मुल्तानी मढ़ी प्राचीन संन्यास परंपरा की एक महत्वपूर्ण कड़ी है, जिसने विभिन्न क्षेत्रों में अखाड़े की परंपरा को आगे बढ़ाया।",
    "auto_page_content_29": "वैकुण्ठी मढ़ी",
    "auto_page_content_30": "वैकुण्ठी मढ़ी आध्यात्मिक साधना, सेवा एवं धार्मिक संस्कारों के संरक्षण के उद्देश्य से कार्यरत परंपरागत मढ़ी है।",
    "auto_page_content_31": "सिंहासनी मढ़ी",
    "auto_page_content_32": "सिंहासनी मढ़ी अखाड़े की प्रतिष्ठित मढ़ियों में से एक है, जो शैव संन्यास परंपरा एवं धार्मिक अनुशासन को सुदृढ़ करती है।",
    "auto_page_content_33": "दरियाव मढ़ी",
    "auto_page_content_34": "दरियाव मढ़ी सेवा, समर्पण एवं संत परंपरा के आदर्शों का पालन करते हुए अखाड़े की सांस्कृतिक धरोहर को संरक्षित करती है।",
    "auto_page_content_35": "दस + चार मढ़ी",
    "auto_page_content_36": "दस + चार मढ़ी अखाड़े की विशिष्ट पारंपरिक शाखाओं में से एक है, जो गुरु-शिष्य परंपरा एवं संगठनात्मक संरचना का अभिन्न भाग है।",
    "auto_page_content_37": "दस + छः मढ़ी",
    "auto_page_content_38": "दस + छः मढ़ी श्री पंचायती अखाड़ा श्री निरंजनी की मान्य परंपरागत मढ़ियों में सम्मिलित है और अखाड़े की आध्यात्मिक एवं धार्मिक परंपराओं के संरक्षण में महत्वपूर्ण भूमिका निभाती है।",
    "auto_page_content_39": "इतिहास",
    "auto_page_content_40": "स्थापना",
    "auto_page_content_41": "गुरु परंपरा",
    "auto_page_content_42": "कुंभ पर्व",
    "auto_page_content_43": "नागा संन्यासी",
    "auto_page_content_44": "वर्तमान स्वरूप",
    "auto_page_content_45": "गुरु कृपा ही जीवन का प्रकाश है",
    "auto_page_content_46": "श्री पंचायती अखाड़ा श्री निरंजनी का इतिहास",
    "auto_page_content_47": "स्थापना एवं उद्देश्य",
    "auto_page_content_48": "निरंजनी अखाड़ा का मूल उद्देश्य धर्म की रक्षा, साधु-संतों का संगठन, वैदिक ज्ञान का संरक्षण तथा सनातन संस्कृति का प्रचार-प्रसार है। अखाड़े में संन्यासियों को शास्त्र एवं शस्त्र दोनों की शिक्षा प्रदान की जाती रही है, जिससे वे समाज तथा धर्म की रक्षा के लिए सदैव तत्पर रहें।",
    "auto_page_content_49": "गुरु-शिष्य परंपरा",
    "auto_page_content_50": "निरंजनी अखाड़े की पहचान उसकी अखंड गुरु-शिष्य परंपरा है। प्रत्येक संन्यासी अपने गुरु से दीक्षा प्राप्त कर वैदिक ज्ञान, योग, तप, संयम तथा सेवा के मार्ग पर अग्रसर होता है। यह परंपरा आज भी उसी श्रद्धा एवं अनुशासन के साथ निरंतर आगे बढ़ रही है।",
    "auto_page_content_51": "कुंभ पर्व में निरंजनी अखाड़ा",
    "auto_page_content_52": "महाकुंभ एवं अर्धकुंभ में निरंजनी अखाड़े का शाही स्नान अत्यंत महत्वपूर्ण माना जाता है। लाखों श्रद्धालु अखाड़े के नागा संन्यासियों एवं संतों के दिव्य दर्शन हेतु उपस्थित होते हैं। यह केवल धार्मिक आयोजन नहीं बल्कि सनातन संस्कृति की महान परंपरा का उत्सव है।",
    "auto_page_content_53": "आध्यात्मिक विरासत",
    "auto_page_content_54": "निरंजनी अखाड़ा वेद, उपनिषद, पुराण, योग, ध्यान, तपस्या एवं भारतीय आध्यात्मिक संस्कृति की अमूल्य धरोहर को संरक्षित करने का कार्य करता है। इसके आश्रम एवं मढ़ियाँ देशभर में धर्म, शिक्षा, सेवा एवं साधना के केंद्र के रूप में कार्यरत हैं।",
    "auto_page_content_55": "आज श्री पंचायती अखाड़ा श्री निरंजनी आधुनिक युग में भी अपनी प्राचीन परंपराओं को अक्षुण्ण रखते हुए धर्म, संस्कृति, शिक्षा, सेवा एवं आध्यात्मिक जागरण के कार्यों में सक्रिय है। देशभर में स्थित इसकी शाखाएँ, मढ़ियाँ एवं संत समाज सनातन धर्म के प्रचार-प्रसार में निरंतर योगदान दे रहे हैं।",
    "auto_page_content_56": "इतिहास की प्रमुख विशेषताएँ",
    "auto_page_content_57": "निरंजनी अखाड़े की शक्ति इसकी अखंड गुरु-शिष्य परंपरा में निहित है, जहाँ आध्यात्मिक ज्ञान, अनुशासन एवं सन्यास संस्कार पीढ़ी-दर-पीढ़ी हस्तांतरित होते हैं।",
    "auto_page_content_58": "धर्म संरक्षण",
    "auto_page_content_59": "अखाड़े का प्रमुख उद्देश्य सनातन धर्म, वैदिक संस्कृति एवं भारतीय आध्यात्मिक विरासत का संरक्षण तथा समाज में धर्म जागरण करना है।",
    "auto_page_content_60": "श्री पंचायती अखाड़ा श्री निरंजनी केवल एक संन्यासी संगठन नहीं, बल्कि सनातन धर्म, वैदिक परंपरा, आध्यात्मिक साधना तथा राष्ट्रधर्म की रक्षा का एक जीवंत केंद्र है। इसकी परंपराएँ सदियों से गुरु-शिष्य संबंध, तप, त्याग, सेवा एवं धर्म संरक्षण के आदर्शों पर आधारित हैं।",
    "auto_page_content_61": "निरंजनी अखाड़े की विशेषताएँ",
    "auto_page_content_62": "श्री पंचायती अखाड़ा श्री निरंजनी भारतीय सनातन परंपरा के उन महान आध्यात्मिक संस्थानों में से एक है जिसने धर्म, साधना एवं संस्कृति के संरक्षण में अमूल्य योगदान दिया है।",
    "auto_page_content_63": "दशनामी संन्यास परंपरा",
    "auto_page_content_64": "आदि शंकराचार्य द्वारा स्थापित दशनामी संन्यास परंपरा के सिद्धांतों का पालन करते हुए अखाड़ा वैदिक ज्ञान एवं आध्यात्मिक अनुशासन का संवाहक है।",
    "auto_page_content_65": "कुंभ की गौरवशाली परंपरा",
    "auto_page_content_66": "महाकुंभ एवं अर्धकुंभ में निरंजनी अखाड़े की शाही पेशवाई और शाही स्नान इसकी प्राचीन परंपरा एवं आध्यात्मिक गौरव का प्रतीक हैं।",
    "auto_page_content_67": "॥ श्री गुरु निरंजन देव ॥",
    "auto_page_content_68": "अखण्डमण्डलाकारं व्याप्तं येन चराचरम् ।तत्पदं दर्शितं येन तस्मै श्रीगुरवे नमः ॥",
    "auto_page_content_69": "अज्ञानतिमिरान्धस्य ज्ञानाञ्जनशलाकया ।चक्षुरुन्मीलितं येन तस्मै श्रीगुरवे नमः ॥",
    "auto_page_content_70": "गुरुर्ब्रह्मा गुरुर्विष्णुः गुरुर्देवो महेश्वरः ।गुरुः साक्षात् परब्रह्म तस्मै श्रीगुरवे नमः ॥",
    "auto_page_content_71": "श्री पंचायती अखाड़ा श्री निरंजनी की गुरु परंपरा",
    "auto_page_content_72": "गुरु परंपरा भारतीय सनातन संस्कृति की आत्मा है। श्री पंचायती\n                                    अखाड़ा श्री निरंजनी में गुरु को ब्रह्मा, विष्णु एवं महेश के स्वरूप के रूप में पूज्य\n                                    माना जाता है। गुरु ही शिष्य को आत्मज्ञान, वैराग्य, तप, योग तथा धर्म के मार्ग पर\n                                    अग्रसर करते हैं। यह अखंड परंपरा सदियों से गुरु से शिष्य तक निरंतर प्रवाहित होती आ\n                                    रही है और आज भी उसी श्रद्धा, अनुशासन एवं समर्पण के साथ जीवित है।",
    "auto_page_content_73": "आध्यात्मिक ज्ञान",
    "auto_page_content_74": "गुरु शिष्य को वेद, उपनिषद, शास्त्र एवं आत्मज्ञान का प्रकाश प्रदान करते हैं।",
    "auto_page_content_75": "संन्यास दीक्षा",
    "auto_page_content_76": "गुरु के मार्गदर्शन में संन्यास की दीक्षा प्राप्त कर साधक धर्म एवं साधना का जीवन प्रारंभ करता है।",
    "auto_page_content_77": "अनुशासन एवं साधना",
    "auto_page_content_78": "गुरु परंपरा तप, संयम, सेवा और आत्मानुशासन का सर्वोच्च आदर्श प्रस्तुत करती है।",

    "new_custom_1": "भूमिका एवं जिम्मेदारियाँ",
    "new_custom_2": "आचार्य महामण्डलेश्वर — श्री पंचायती अखाड़ा श्री निरंजनी",
    "new_custom_3": "निरंजन पीठाधीश्वर",
    "new_custom_4": "सर्वोच्च आध्यात्मिक गुरु — श्री पंचायती अखाड़ा श्री निरंजनी",
    "new_custom_5": "सिद्धपीठ श्री दक्षिण काली मंदिर, हरिद्वार के पीठाधीश्वर",
    "new_custom_6": "नागा संन्यास परंपरा के आध्यात्मिक मार्गदर्शक",
    "new_custom_7": "सनातन धर्म एवं वेदांत के प्रचारक",
    "new_custom_8": "प्रेम का अर्थ सेवा है, और सेवा का अर्थ है ईश्वर को प्रसन्न करना।",
    "new_custom_9": "सचिव — श्री पंचायती अखाड़ा श्री निरंजनी",
    "new_custom_10": "अध्यक्ष — मनसा देवी मंदिर ट्रस्ट, हरिद्वार",
    "new_custom_11": "अखिल भारतीय अखाड़ा परिषद के पूर्व अध्यक्ष",
    "new_custom_12": "सनातन धर्म और संस्कृति के प्रमुख संरक्षक",
    "new_custom_13": "हरिद्वार में धार्मिक और सामाजिक कार्यों के प्रमुख मार्गदर्शक",
    "new_custom_14": "कुंभ मेले और धार्मिक आयोजनों के प्रमुख व्यवस्थापक",
    "new_custom_15": "नर सेवा ही नारायण सेवा है। सेवा वह है जिसमें न कोई अपेक्षा हो और न कोई स्वार्थ।",

    "auto_key_1": "मुख्यपृष्ठ",
    "auto_key_2": "हमारे\n                                        बारे में",
    "auto_key_3": "इतिहास",
    "auto_key_4": "गुरु\n                                        परंपरा",
    "auto_key_5": "मढ़ियाँ",
    "auto_key_6": "संत एवं\n                                        महंत",
    "auto_key_7": "महामंडलेश्वर",
    "auto_key_8": "महंत",
    "auto_key_9": "Sermons",
    "auto_key_10": "Sermon\n                                                Details",
    "auto_key_11": "Our\n                                                Ministries",
    "auto_key_12": "Ministry\n                                                Details",
    "auto_key_13": "Pastor",
    "auto_key_14": "Pastor\n                                                Details",
    "auto_key_15": "Testimonials",
    "auto_key_16": "Image\n                                                Gallery",
    "auto_key_17": "Video\n                                                Gallery",
    "auto_key_18": "FAQs",
    "auto_key_19": "404",
    "auto_key_20": "अखाड़े\n                                        की शाखाएँ",
    "auto_key_21": "देशभर की\n                                                शाखाएँ",
    "auto_key_22": "अखाड़े की\n                                                शाखाएँ",
    "auto_key_23": "हमारी\n                                                शाखाएँ",
    "auto_key_24": "शाखा केंद्र",
    "auto_key_25": "गतिविधियाँ",
    "auto_key_26": "कार्यक्रम",
    "auto_key_27": "कुंभ मेला",
    "auto_key_28": "चित्रावली",
    "auto_key_29": "समाचार",
    "auto_key_30": "दान",
    "auto_key_31": "संपर्क",
    "auto_key_32": "॥ ॐ गुरु निरंजन देवाय\n                                नमः ॥",
    "auto_key_33": "पंचायती अखाड़ा\n                                श्री निरंजनी",
    "auto_key_34": "हमारे\n                                बारे में",
    "auto_key_35": "इतिहास\n                                जानें",
    "auto_key_36": "आदि शंकराचार्य की महान दशनामी परंपरा से प्रेरित, पंचायती अखाड़ा\n                                श्री निरंजनी सदियों से सनातन धर्म की रक्षा, आध्यात्मिक चेतना के प्रसार, संत परंपरा के\n                                संरक्षण तथा मानव कल्याण के लिए समर्पित है।",
    "auto_key_37": "सदियों की आध्यात्मिक परंपरा",
    "auto_key_38": "स्वयंसेवकों का विशाल समूह",
    "auto_key_39": "सनातन धर्म सेवा एवं संरक्षण",
    "auto_key_40": "हमारी कहानी, आस्था,\n                                मिशन और विजन",
    "auto_key_41": "पंचायती अखाड़ा श्री\n                                निरंजनी , महान दार्शनिक एवं धर्मप्रवर्तक आदि शंकराचार्य द्वारा स्थापित दशनामी संप्रदाय\n                                की एक अत्यंत प्राचीन, तेजस्वी और प्रतिष्ठित शाखा है। इस अखाड़े की स्थापना विक्रम संवत\n                                १४२९ (ईस्वी १४७२) में हुई थी।",
    "auto_key_42": "गुरु परंपरा",
    "auto_key_43": "आदि गुरु शंकराचार्य द्वारा स्थापित दशनामी संन्यास\n                                        परंपरा का संरक्षण एवं संवर्धन।",
    "auto_key_44": "धर्म एवं समाज सेवा",
    "auto_key_45": "सनातन धर्म के प्रचार, आध्यात्मिक जागरण एवं जनकल्याण\n                                        के लिए निरंतर समर्पित।",
    "auto_key_46": "और अधिक जानें",
    "auto_key_47": "श्री महंत रविन्द्रपुरी महाराज",
    "auto_key_48": "सचिव – पंचायती अखाड़ा श्री निरंजनी अध्यक्ष – मनसा देवी मंदिर ट्रस्ट",
    "auto_key_49": "॥ ॐ नमः शिवाय ॥",
    "auto_key_50": "॥ ॐ गुरु निरंजन देव नमः ॥",
    "auto_key_51": "हमारी परंपराएँ",
    "auto_key_52": "हमारी धार्मिक\n                            परंपराएँ और अनुष्ठान",
    "auto_key_53": "गुरु\n                                                    परंपरा",
    "auto_key_54": "आदि गुरु शंकराचार्य की दशनामी परंपरा का पालन\n                                                करते हुए गुरु-शिष्य परंपरा का संरक्षण एवं संवर्धन।",
    "auto_key_55": "अधिक जानें",
    "auto_key_56": "सनातन धर्म\n                                                    सेवा",
    "auto_key_57": "सनातन धर्म के संरक्षण, आध्यात्मिक जागरण एवं समाज\n                                                सेवा के लिए निरंतर समर्पित।",
    "auto_key_58": "कुंभ एवं\n                                                    धार्मिक आयोजन",
    "auto_key_59": "कुंभ मेला, शाही स्नान एवं अन्य धार्मिक आयोजनों\n                                                में अखाड़े की गौरवशाली सहभागिता।",
    "auto_key_60": "धर्म प्रचार\n                                                    एवं प्रचार",
    "auto_key_61": "सनातन संस्कृति का प्रचार-प्रसार, व्याख्यानमालाएं\n                                                एवं धार्मिक शिक्षा कार्यक्रम।",
    "auto_key_62": "हमारा उद्देश्य",
    "auto_key_63": "श्री गुरु\n                                निरंजन देव एवं दशनामी संन्यास परंपरा",
    "auto_key_64": "श्री गुरु निरंजन देव\n                                की पावन परंपरा में स्थापित श्री पंचायती अखाड़ा श्री निरंजनी, सनातन वैदिक परंपरा एवं\n                                दशनामी संन्यास परंपरा का अनुसरण करता है। इस परंपरा में गुरु-शिष्य संबंध, आध्यात्मिक\n                                साधना तथा धर्म संरक्षण को सर्वोच्च स्थान प्राप्त है।",
    "auto_key_65": "श्री १००८ श्री आचार्य महामण्डलेश्वर स्वामी श्री कैलाशानन्द\n                                    गिरि जी महाराज",
    "auto_key_66": "वर्तमान आचार्य गुरु",
    "auto_key_67": "गुरु परंपरा जानें",
    "auto_key_68": "श्री गुरु\n                                                    निरंजन देव स्तुति",
    "auto_key_69": "निरंजन देव स्तुति एवं गुरु परंपरा के माध्यम से\n                                                आध्यात्मिक साधना और गुरु-भक्ति का मार्ग।",
    "auto_key_70": "अधिक\n                                                जानें",
    "auto_key_71": "आदि गुरु शंकराचार्य से चली आ रही दशनामी संन्यास\n                                                परंपरा एवं वर्तमान आचार्य गुरु की गौरवशाली परंपरा.",
    "auto_key_72": "कुंभ\n                                                    पर्व",
    "auto_key_73": "हरिद्वार, प्रयाग, उज्जैन एवं नासिक कुंभ पर्व का\n                                                आध्यात्मिक महत्व एवं अखाड़े की गौरवशाली परंपरा।",
    "auto_key_74": "मढ़ियाँ एवं\n                                                    शाखाएँ",
    "auto_key_75": "श्री पंचायती निरंजनी अखाड़े की 18 मढ़ियाँ तथा\n                                                भारतभर में स्थापित आध्यात्मिक केंद्र।",
    "auto_key_76": "प्रमुख विरासत",
    "auto_key_77": "पंचायती अखाड़ा श्री\n                            निरंजनी की आध्यात्मिक एवं धार्मिक धरोहर",
    "auto_key_78": "सात\n                                        अखाड़े",
    "auto_key_79": "शैव संन्यासी परंपरा के सात\n                                            प्रमुख अखाड़ों में श्री पंच निरंजनी अखाड़ा का विशिष्ट स्थान है।",
    "auto_key_80": "Read More",
    "auto_key_81": "18\n                                        मढ़ियाँ",
    "auto_key_82": "देशभर में स्थापित अठारह\n                                            मढ़ियाँ आध्यात्मिक साधना एवं परंपरा के प्रमुख केंद्र हैं।",
    "auto_key_83": "चार\n                                        महावाक्य",
    "auto_key_84": "अहं ब्रह्मास्मि •\n                                            अयमात्मा ब्रह्म • तत्त्वमसि • प्रज्ञानं ब्रह्म",
    "auto_key_85": "गुरु परंपरा से कुंभ पर्व तक, पंचायती अखाड़ा श्री निरंजनी की\n                            आध्यात्मिक धरोहर का अवलोकन करें",
    "auto_key_86": "सभी विषय देखें →",
    "auto_key_87": "“परम पूज्य श्री 1008 श्री आचार्य महामण्डलेश्वर स्वामी श्री\n                                    कैलाशानन्द गिरि जी\n                                    महाराज”",
    "auto_key_88": "जानें",
    "auto_key_89": "आचार्य संदेश",
    "auto_key_90": "परम पूज्य श्री\n                                1008 श्री आचार्य\n                                महामण्डलेश्वर स्वामी श्री कैलाशानन्द गिरि जी महाराज",
    "auto_key_91": "आचार्य गुरु का\n                                जीवन सनातन धर्म,\n                                गुरु-शिष्य परंपरा एवं आध्यात्मिक साधना के प्रति पूर्ण समर्पण का प्रतीक है। उनके\n                                मार्गदर्शन में श्री पंचायती अखाड़ा श्री निरंजनी अपनी प्राचीन परंपराओं, आध्यात्मिक\n                                मूल्यों तथा धर्म संरक्षण के संकल्प को निरंतर आगे बढ़ा रहा है।",
    "auto_key_92": "पद:",
    "auto_key_93": "आचार्य महामण्डलेश्वर",
    "auto_key_94": "परंपरा:",
    "auto_key_95": "दशनामी संन्यास परंपरा",
    "auto_key_96": "संदेश पढ़ें",
    "auto_key_97": "सनातन ज्ञान\n                            एवं आध्यात्मिक परंपरा",
    "auto_key_98": "द्वादश\n                                                        ज्योतिर्लिंग",
    "auto_key_99": "भगवान शिव को समर्पित बारह ज्योतिर्लिंग भारत\n                                                    की आध्यात्मिक चेतना के केंद्र हैं।",
    "auto_key_100": "सप्तमोक्षदायिका पुरी",
    "auto_key_101": "अयोध्या, मथुरा, माया, काशी, कांची, अवन्तिका\n                                                    एवं द्वारका का धार्मिक महत्व।",
    "auto_key_102": "पंचकन्या",
    "auto_key_103": "अहल्या, द्रौपदी, सीता, तारा एवं मन्दोदरी के\n                                                    स्मरण का महत्व।",
    "auto_key_104": "श्री पंचायती निरंजनी अखाड़ा की आध्यात्मिक धरोहर एवं सनातन परंपराओं\n                            का अवलोकन करें",
    "auto_key_105": "सभी अनुभाग देखें",
    "auto_key_106": "श्री महंत\n                                रविन्द्रपुरी महाराज",
    "auto_key_107": "सचिव – पंचायती\n                                अखाड़ा श्री निरंजनी अध्यक्ष – मनसा देवी मंदिर ट्रस्ट, हरिद्वार",
    "auto_key_108": "श्री महंत रविन्द्रपुरी\n                                महाराज, पंचायती अखाड़ा श्री निरंजनी के सचिव\n                                एवं मनसा देवी मंदिर ट्रस्ट, हरिद्वार के अध्यक्ष हैं। गुरु परंपरा, सनातन धर्म के संरक्षण\n                                तथा आध्यात्मिक परंपराओं के संवर्धन में उनका महत्वपूर्ण योगदान है। उनके मार्गदर्शन में\n                                अखाड़ा अपनी प्राचीन परंपराओं, धार्मिक आयोजनों एवं आध्यात्मिक मूल्यों को आगे बढ़ाने के\n                                लिए निरंतर कार्यरत है।",
    "auto_key_109": "और\n                                जानें",
    "auto_key_110": "अखाड़े सात",
    "auto_key_111": "दशनामी संन्यास\n                                परंपरा के सात प्रमुख\n                                अखाड़े",
    "auto_key_112": "भारत की समृद्ध\n                                आध्यात्मिक परंपरा में, दशनामी\n                                संन्यास अखाड़े महत्वपूर्ण भूमिका निभाते हैं। ये अखाड़े हजारों वर्षों से सनातन\n                                धर्म के मूल्यों, दर्शनों और परंपराओं को संरक्षण और संवर्धन प्रदान कर रहे हैं।",
    "auto_key_113": "View All\n                                Stories",
    "auto_key_114": "“श्री पंच निरंजनी अखाड़ा”",
    "auto_key_115": "दशनामी शैव संन्यास परंपरा के प्रमुख एवं\n                                                        प्रतिष्ठित अखाड़ों में से\n                                                        एक। यह अखाड़ा गुरु-शिष्य परंपरा, वैदिक ज्ञान, तप, साधना तथा\n                                                        सनातन धर्म के संरक्षण के लिए समर्पित है। कुंभ पर्व में इसकी\n                                                        विशिष्ट भूमिका एवं शाही स्नान की गौरवशाली परंपरा है।",
    "auto_key_116": "“श्री पंच जूना अखाड़ा”",
    "auto_key_117": "शैव संन्यासी परंपरा का एक प्रतिष्ठित\n                                                        अखाड़ा, जो साधना,\n                                                        गुरु-परंपरा तथा सनातन धर्म की सेवा के लिए समर्पित है। इसके\n                                                        संन्यासी आध्यात्मिक जीवन एवं वैदिक मूल्यों के प्रचार में सक्रिय\n                                                        रहते हैं।",
    "auto_key_118": "“श्री पंच आनंद अखाड़ा”",
    "auto_key_119": "आध्यात्मिक अनुशासन, वैराग्य एवं वेदांत\n                                                        पर आधारित दशनामी परंपरा का\n                                                        महत्वपूर्ण अखाड़ा। साधना, संन्यास एवं धर्म प्रचार इसकी प्रमुख\n                                                        विशेषताएँ हैं।",
    "auto_key_120": "“श्री पंच आवाहन अखाड़ा”",
    "auto_key_121": "भगवान शिव की उपासना तथा दशनामी संन्यास\n                                                        परंपरा के संरक्षण के लिए\n                                                        समर्पित अखाड़ा। आध्यात्मिक साधना, वैदिक अध्ययन एवं धार्मिक\n                                                        परंपराओं के पालन में इसका विशेष स्थान है।",
    "auto_key_122": "“श्री पंच अटल अखाड़ा”",
    "auto_key_123": "दृढ़ आध्यात्मिक अनुशासन, तपस्या एवं\n                                                        संन्यास जीवन के आदर्शों का\n                                                        पालन करने वाला प्रमुख शैव अखाड़ा। यह धर्म, संस्कृति एवं वैदिक\n                                                        परंपराओं के संरक्षण में योगदान देता है।",
    "auto_key_124": "“श्री पंच निर्वाणी अखाड़ा”",
    "auto_key_125": "“श्री पंच अग्नि अखाड़ा”",
    "auto_key_126": "वैदिक यज्ञ, तप, ब्रह्मचर्य एवं\n                                                        आध्यात्मिक साधना की परंपरा से\n                                                        जुड़ा दशनामी अखाड़ा। यह त्याग, अनुशासन एवं ज्ञान पर विशेष बल\n                                                        देता है।",
    "auto_key_127": "शैव अखाड़े",
    "auto_key_128": "वैष्णव अखाड़े",
    "auto_key_129": "उदासीन अखाड़े",
    "auto_key_130": "निर्मल अखाड़ा",
    "auto_key_131": "13",
    "auto_key_132": "कुल मान्यता प्राप्त अखाड़े",
    "auto_key_133": "/5",
    "auto_key_134": "4.9",
    "auto_key_135": "Based on 2500+ reviews",
    "auto_key_136": "Frequently Asked\n                                Questions",
    "auto_key_137": "Answers to the\n                                question you might have about",
    "auto_key_138": "Q1. श्री पंचायती निरंजनी अखाड़ा किन अखाड़ों में सम्मिलित है?",
    "auto_key_139": "1) श्री पंच निरंजनी अखाड़ा 2) श्री पंच आनंद अखाड़ा 3) श्री पंच आवाहन अखाड़ा 4) श्री पंच अटल अखाड़ा 5) श्री पंच निर्वाणी अखाड़ा 6) श्री पंच अग्नि अखाड़ा 7) श्री पंच जूना अखाड़ा.",
    "auto_key_140": "Q2.श्री पंचायती निरंजनी अखाड़े में कुल कितनी मढ़ियाँ हैं?",
    "auto_key_141": "श्री पंचायती निरंजनी अखाड़े के अंतर्गत 18 मढ़ियाँ\n                                            हैं।",
    "auto_key_142": "Q3. अखाड़े के चार महावाक्य कौन-कौन से हैं?",
    "auto_key_143": "1) अहं ब्रह्मास्मि 2) अयमात्मा ब्रह्म 3) तत्त्वमसि 4) प्रज्ञानं ब्रह्म",
    "auto_key_144": "Q4. कुंभ पर्व किन-किन स्थानों पर आयोजित होता है?",
    "auto_key_145": "कुंभ पर्व चार स्थानों पर आयोजित होता है— 1) हरिद्वार 2) प्रयाग 3) उज्जैन 4) नासिक",
    "auto_key_146": "Q5. वर्तमान आचार्य गुरु कौन हैं?",
    "auto_key_147": "परमहंस परिव्राजकाचार्य श्रीमद् ब्रह्मनिष्ठ पूज्यपाद\n                                            श्री निरंजन पीठाधीश्वर श्री श्री 1008 आचार्य महामण्डलेश्वर स्वामी श्री\n                                            कैलाशानन्द गिरि जी महाराज।",
    "auto_key_148": "॥ श्री गुरु निरंजन देव\n                                स्तुति ॥",
    "auto_key_149": "ॐकारबिन्दु\n                                संयुक्तं नित्यं ध्यायन्ति योगिनः। कामदं मोक्षदं चैव ॐकाराय नमो",
    "auto_key_150": "नमः॥",
    "auto_key_151": "श्री गुरु निरंजन देव स्तुति-",
    "auto_key_152": "विशेष जानकारी",
    "auto_key_153": "निरंजनी परंपरा की\n                            विशिष्ट आध्यात्मिक धरोहर",
    "auto_key_154": "आदि शंकराचार्य द्वारा स्थापित दशनामी संन्यास परंपरा भारतीय\n                                    आध्यात्मिक जीवन, वैदिक ज्ञान एवं सन्यास धर्म की आधारशिला है।",
    "auto_key_155": "और जानें",
    "auto_key_156": "अखाड़ों का इतिहास",
    "auto_key_157": "भारतीय संत परंपरा में अखाड़ों की स्थापना धर्म रक्षा,\n                                    आध्यात्मिक साधना तथा वैदिक संस्कृति के संरक्षण के उद्देश्य से हुई।",
    "auto_key_158": "गुरु–शिष्य परंपरा",
    "auto_key_159": "गुरु से शिष्य तक ज्ञान, तप, त्याग और धर्म की परंपरा निरंतर\n                                    प्रवाहित होती रही है, जो अखाड़े की मूल पहचान है।",
    "auto_key_160": "श्री पंचायती निरंजनी अखाड़ा",
    "auto_key_161": "आदि\n                                शंकराचार्य द्वारा स्थापित दशनामी शैव संन्यास परंपरा का एक प्रमुख अखाड़ा, जो सनातन धर्म,\n                                गुरु-शिष्य परंपरा एवं आध्यात्मिक संस्कृति के संरक्षण के लिए समर्पित है।",
    "auto_key_162": "सनातन परंपरा से जुड़े रहें",
    "auto_key_163": "॥ ॐ गुरु निरंजन देवाय नमः ॥",
    "auto_key_164": "Quick Links",
    "auto_key_165": "मुखपृष्ठ",
    "auto_key_166": "हमारे बारे में",
    "auto_key_167": "शाखाएँ",
    "auto_key_168": "कुंभ पर्व",
    "auto_key_169": "Our Services",
    "auto_key_170": "श्री गुरु निरंजन देव\n                                        स्तुति",
    "auto_key_171": "चार महावाक्य",
    "auto_key_172": "सप्त मोक्षदायिनी पुरियाँ",
    "auto_key_173": "द्वादश ज्योतिर्लिंग",
    "auto_key_174": "गुरुकार्तिकेय स्तोत्र",
    "auto_key_175": "सप्त चिरंजीवी मंत्र",
    "auto_key_176": "📍 गणेशघाट, मायापुर, हरिद्वार, उत्तराखण्ड 📍 प्रयागराज (उत्तर प्रदेश) 📍 काशी / वाराणसी (उत्तर प्रदेश) 📍 उज्जैन (मध्य प्रदेश) 📍 त्र्यंबकेश्वर, नासिक (महाराष्ट्र)",
    "auto_key_177": "Copyright © 2026 पंचायती अखाड़ा श्री निरंजनी. All Rights Reserved.\n                                Digital Experience by",
    "auto_key_178": "ATHInnovations.",
    "auto_key_179": "सनातन धर्म, गुरु-शिष्य परंपरा और\n                                आध्यात्मिक साधना की गौरवशाली विरासत",
    "auto_key_180": "श्री पंचायती निरंजनी अखाड़ा दशनामी शैव संन्यास\n                                परंपरा के प्रमुख एवं प्राचीन अखाड़ों में से एक है। आदि शंकराचार्य द्वारा स्थापित इस महान\n                                परंपरा का उद्देश्य सनातन धर्म का संरक्षण, वैदिक ज्ञान का प्रसार, गुरु-शिष्य परंपरा का\n                                संवर्धन तथा समाज में आध्यात्मिक जागरण करना है। सदियों से यह अखाड़ा तप, त्याग, सेवा और\n                                धर्म रक्षा के आदर्शों का पालन करते हुए भारतीय आध्यात्मिक संस्कृति का मार्गदर्शन करता आ\n                                रहा है।",
    "auto_key_181": "मिशन",
    "auto_key_182": "सनातन धर्म का संरक्षण, वैदिक परंपराओं का संवर्धन, गुरु-शिष्य परंपरा को सुदृढ़\n                                        करना तथा समाज में आध्यात्मिक चेतना, सेवा और संस्कारों का प्रसार करना।",
    "auto_key_183": "हमारा विज़न",
    "auto_key_184": "ऐसे समाज का निर्माण जहाँ धर्म, संस्कृति, आध्यात्मिकता और मानवीय मूल्यों के माध्यम\n                                        से आने वाली पीढ़ियाँ सनातन परंपरा से जुड़ी रहें और राष्ट्र तथा मानवता के कल्याण\n                                        में योगदान दें।",
    "auto_key_185": "इतिहास जानें",
    "auto_key_186": "श्रीमहंत रविन्द्र पुरी जी महाराज",
    "auto_key_187": "अध्यक्ष, श्री पंचायती निरंजनी अखाड़ा",
    "auto_key_188": "श्री पंचायती\n                                अखाड़ा श्री निरंजनी दशनामी संन्यास परंपरा का एक प्रतिष्ठित एवं आध्यात्मिक अखाड़ा है, जो\n                                सनातन वैदिक संस्कृति, गुरु-शिष्य परंपरा तथा धर्मरक्षा के महान उद्देश्य के प्रति समर्पित\n                                है। अखाड़ा भगवान शिव की उपासना, वैदिक ज्ञान, तप, त्याग एवं संन्यास जीवन की गौरवशाली\n                                परंपरा का पालन करते हुए समाज में आध्यात्मिक चेतना का प्रसार करता है।",
    "auto_key_189": "इस पावन\n                                परंपरा में गुरु का स्थान सर्वोच्च माना गया है। अखाड़े में गुरु-भक्ति, वेदांत दर्शन, चार\n                                महावाक्य, द्वादश ज्योतिर्लिंग, सप्त मोक्षदायिनी पुरियों तथा सनातन धर्म के मूल सिद्धांतों\n                                का अध्ययन, संरक्षण एवं प्रचार निरंतर किया जाता है।",
    "auto_key_190": "श्री पंचायती अखाड़ा श्री निरंजनी भारत के सात प्रमुख अखाड़ों में से एक है। इसकी परंपरा\n                                    देशभर के प्रमुख तीर्थस्थलों, मढ़ियों एवं धार्मिक केंद्रों के माध्यम से सनातन\n                                    संस्कृति को सुदृढ़ करने का कार्य करती है। अखाड़ा विशेष रूप से कुंभ, अर्धकुंभ एवं\n                                    सिंहस्थ जैसे महान धार्मिक आयोजनों में सक्रिय भूमिका निभाता है तथा शाही स्नान की\n                                    प्राचीन परंपरा का निर्वहन करता है।",
    "auto_key_191": "अखाड़े की\n                                आध्यात्मिक साधना का केंद्र गुरु-भक्ति, तप, संयम, सेवा और आत्मज्ञान है। इसका उद्देश्य\n                                केवल संन्यास परंपरा का संरक्षण ही नहीं, बल्कि समाज में धर्म, सदाचार, राष्ट्रसेवा तथा\n                                मानव कल्याण के मूल्यों को स्थापित करना भी है। अखाड़े से जुड़े संत-महात्मा अपने जीवन को\n                                लोककल्याण एवं सनातन धर्म के प्रचार-प्रसार के लिए समर्पित करते हैं।",
    "auto_key_192": "तप • त्याग\n                                • सेवा • साधना • धर्मरक्षा • गुरु-भक्ति",
    "auto_key_193": "श्री पंचायती\n                                अखाड़ा श्री निरंजनी की परंपरा गुरु के प्रति पूर्ण समर्पण, शास्त्रों के अध्ययन, साधना की\n                                पवित्रता तथा आत्मबोध की दिशा में सतत प्रयास पर आधारित है। गुरु को ब्रह्मस्वरूप मानते हुए\n                                उनके उपदेशों का अनुसरण करना ही साधक के आध्यात्मिक जीवन का मूल आधार माना जाता है। अखाड़े\n                                में गुरु-शिष्य परंपरा केवल ज्ञान का आदान-प्रदान नहीं, बल्कि जीवन के प्रत्येक क्षेत्र में\n                                संस्कार, अनुशासन और आध्यात्मिक उन्नति का माध्यम है।",
    "auto_key_194": "सनातन धर्म एवं वैदिक संस्कृति का संरक्षण।",
    "auto_key_195": "गुरु-शिष्य परंपरा का संवर्धन।",
    "auto_key_196": "तप, त्याग एवं साधना की भावना को सुदृढ़ करना।",
    "auto_key_197": "वेदांत एवं आध्यात्मिक ज्ञान का प्रचार-प्रसार।",
    "auto_key_198": "धर्म, सेवा एवं लोककल्याण के कार्यों को बढ़ावा देना।",
    "auto_key_199": "भारतीय आध्यात्मिक विरासत को आने वाली पीढ़ियों तक सुरक्षित पहुँचाना।",
    "auto_key_200": "हमारे मूल सिद्धांत",
    "auto_key_201": "पंचायती अखाड़ा श्री निरंजनी के आध्यात्मिक\n                            सिद्धांत",
    "auto_key_202": "गुरु-शिष्य परंपरा",
    "auto_key_203": "गुरु को ब्रह्मस्वरूप मानते हुए उनके उपदेशों, आशीर्वाद एवं ज्ञान के माध्यम से आत्मबोध\n                                    और मोक्ष के मार्ग पर अग्रसर होना ही हमारी सर्वोच्च परंपरा है।",
    "auto_key_204": "वेदांत एवं चार महावाक्यत",
    "auto_key_205": "अखाड़ा अद्वैत वेदांत की परंपरा का अनुसरण करता है। चार महावाक्य आत्मा और ब्रह्म की\n                                    एकता का संदेश देते हैं तथा साधक को आत्मज्ञान की ओर प्रेरित करते हैं।",
    "auto_key_206": "तप, त्याग एवं साधना",
    "auto_key_207": "संयम, तपस्या, वैराग्य, सेवा एवं शिवभक्ति के माध्यम से आत्मशुद्धि और लोककल्याण का\n                                    मार्ग ही संन्यासी जीवन का मूल आधार है।",
    "auto_key_208": "सनातन धर्म, गुरु-भक्ति एवं वेदांत पर आधारित हमारे आध्यात्मिक सिद्धांतों को जानें —",
    "auto_key_209": "सभी सिद्धांत देखें",
    "auto_key_210": "आध्यात्मिक विरासत",
    "auto_key_211": "निरंजनी अखाड़े की अमूल्य आध्यात्मिक धरोहर",
    "auto_key_212": "श्री पंचायती अखाड़ा श्री निरंजनी केवल एक संन्यासी परंपरा नहीं, बल्कि सनातन धर्म की जीवंत आध्यात्मिक विरासत है। इसकी साधना, शास्त्र, गुरु परंपरा और धर्मरक्षा की भावना आज भी करोड़ों श्रद्धालुओं को प्रेरित करती है।",
    "auto_key_213": "शास्त्रीय परंपरा",
    "auto_key_214": "वेद, उपनिषद, चार महावाक्य, स्तोत्र एवं वैदिक ज्ञान का अध्ययन, संरक्षण और प्रचार अखाड़े की प्रमुख आध्यात्मिक परंपराओं में सम्मिलित है।",
    "auto_key_215": "तीर्थ एवं आध्यात्मिक केंद्र",
    "auto_key_216": "हरिद्वार, प्रयागराज, काशी, उज्जैन, त्र्यंबकेश्वर सहित अनेक पवित्र स्थलों पर स्थित मढ़ियाँ साधना, सेवा और संत परंपरा के प्रमुख केंद्र हैं।",
    "auto_key_217": "आध्यात्मिक विरासत जानें",
    "auto_key_218": "हमारा नेतृत्व",
    "auto_key_219": "पंचायती अखाड़ा श्री निरंजनी का वर्तमान आध्यात्मिक नेतृत्व",
    "auto_key_220": "परम पूज्य श्री श्री १००८ आचार्य महामण्डलेश्वर निरंजन पीठाधीश्वर स्वामी कैलाशानन्द गिरि जी महाराज",
    "auto_key_221": "अध्यक्ष",
    "auto_key_222": "महंत ओंकार गिरि जी महाराज",
    "auto_key_223": "सचिव",
    "auto_key_224": "सनातन धर्म की अखंड परंपरा को संतों के मार्गदर्शन में आगे बढ़ाते हुए श्री पंचायती अखाड़ा श्री निरंजनी राष्ट्र, धर्म और संस्कृति की सेवा के लिए निरंतर समर्पित है।",
    "auto_key_225": "अखाड़े की विशेषताएँ",
    "auto_key_226": "सनातन धर्म की रक्षा, साधु परंपरा और आध्यात्मिक नेतृत्व का गौरवशाली केंद्र",
    "auto_key_227": "श्री पंचायती अखाड़ा श्री निरंजनी दशनामी शैव संन्यास परंपरा का प्रमुख अखाड़ा है। इसकी स्थापना धर्म, संस्कृति, वेद-शास्त्र, संन्यास परंपरा तथा राष्ट्रधर्म की रक्षा के उद्देश्य से की गई। आज भी यह अखाड़ा आध्यात्मिक साधना, गुरु-शिष्य परंपरा और सनातन संस्कृति के संरक्षण में अग्रणी भूमिका निभा रहा है।",
    "auto_key_228": "ई.",
    "auto_key_229": "108",
    "auto_key_230": "स्थापना वर्ष",
    "auto_key_231": "दशनामी शैव अखाड़ों में एक प्रमुख अखाड़ा",
    "auto_key_232": "आदि शंकराचार्य की दशनामी संन्यास परंपरा का गौरवशाली अंग।",
    "auto_key_233": "वेद, शास्त्र, तप, योग और सनातन संस्कृति के संरक्षण हेतु समर्पित।",
    "auto_key_234": "अखाड़े का इतिहास जानें",
    "auto_key_235": "परंपरा का संदेश",
    "auto_key_236": "श्री पंचायती अखाड़ा श्री निरंजनी — सनातन साधना का अमर प्रतीक",
    "auto_key_237": "श्री पंचायती अखाड़ा श्री निरंजनी केवल एक अखाड़ा नहीं, बल्कि सनातन धर्म, वेद-वेदांत, तप, त्याग और गुरु-शिष्य परंपरा का जीवंत केंद्र है। इसकी स्थापना धर्म की रक्षा, संत समाज के संगठन तथा आध्यात्मिक चेतना के प्रसार के उद्देश्य से हुई। आज भी अखाड़ा राष्ट्र, संस्कृति और मानवता की सेवा के लिए निरंतर समर्पित है।",
    "auto_key_238": "अखाड़े के बारे में जानें",
    "auto_key_239": "हमारे प्रमुख केंद्र",
    "auto_key_240": "पंचायती अखाड़ा श्री निरंजनी के प्रमुख पीठ एवं केंद्र",
    "auto_key_241": "श्री पंचायती अखाड़ा श्री निरंजनी की आध्यात्मिक एवं प्रशासनिक गतिविधियाँ भारत के प्रमुख तीर्थ क्षेत्रों में संचालित होती हैं। ये केंद्र साधु-संतों, श्रद्धालुओं एवं सनातन परंपरा के संरक्षण के प्रमुख आधार हैं।",
    "auto_key_242": "सभी केंद्र देखें",
    "auto_key_243": "“हरिद्वार (मुख्य पीठ)”",
    "auto_key_244": "📍 गणेश घाट, मायापुर, हरिद्वार, उत्तराखण्ड",
    "auto_key_245": "श्री पंचायती अखाड़ा श्री निरंजनी का मुख्यालय एवं प्रमुख प्रशासनिक केंद्र।",
    "auto_key_246": "“प्रयागराज”",
    "auto_key_247": "📍 दारागंज, प्रयागराज, उत्तर प्रदेश",
    "auto_key_248": "महाकुंभ एवं माघ मेले के दौरान अखाड़े की प्रमुख गतिविधियों का केंद्र।",
    "auto_key_249": "उज्जैन",
    "auto_key_250": "📍 उज्जैन, मध्य प्रदेश",
    "auto_key_251": "सिंहस्थ महापर्व एवं शाही स्नान में अखाड़े का प्रमुख केंद्र।",
    "auto_key_252": "त्र्यंबकेश्वर, नासिक",
    "auto_key_253": "📍 नासिक, महाराष्ट्र",
    "auto_key_254": "कुंभ पर्व एवं दशनामी संन्यास परंपरा से जुड़ा प्रमुख धार्मिक केंद्र।",
    "auto_key_255": "प्रमुख आध्यात्मिक केंद्र",
    "auto_key_256": "904",
    "auto_key_257": "स्थापना",
    "auto_key_258": "कुंभ नगरी",
    "auto_key_259": "दशनामी शैव अखाड़ों में प्रमुख",
    "auto_key_260": "+ वर्ष",
    "auto_key_261": "1100",
    "auto_key_262": "गौरवशाली परंपरा",
    "history_1": "इतिहास",
    "history_2": "श्री पंचायती अखाड़ा श्री निरंजनी की गौरवशाली परंपरा",
    "history_3": "स्थापना",
    "history_4": "गुरु परंपरा",
    "history_5": "मढ़ियाँ",
    "history_6": "कुंभ पर्व",
    "history_7": "नागा संन्यासी",
    "history_8": "वर्तमान स्वरूप",
    "history_9": "गुरु कृपा ही जीवन का प्रकाश है",
    "history_10": "श्री पंचायती अखाड़ा श्री निरंजनी का इतिहास",
    "history_11": "श्री पंचायती अखाड़ा श्री निरंजनी दशनामी संन्यास परंपरा के प्रमुख एवं प्राचीन अखाड़ों में से एक है। इसकी स्थापना सनातन धर्म की रक्षा, वेद-शास्त्रों के प्रचार, संन्यास परंपरा के संरक्षण तथा समाज में आध्यात्मिक चेतना के प्रसार के उद्देश्य से की गई। यह अखाड़ा आदि शंकराचार्य द्वारा स्थापित दशनामी परंपरा का एक महत्वपूर्ण अंग माना जाता है। <br><br>\n                                सदियों से निरंजनी अखाड़ा धर्म, तप, योग, त्याग एवं गुरु-शिष्य परंपरा का केंद्र रहा है। महाकुंभ, अर्धकुंभ तथा अन्य धार्मिक आयोजनों में इसकी गौरवशाली उपस्थिति सनातन संस्कृति की जीवंत पहचान है।",
    "history_12": "स्थापना एवं उद्देश्य",
    "history_13": "निरंजनी अखाड़ा का मूल उद्देश्य धर्म की रक्षा, साधु-संतों का संगठन, वैदिक ज्ञान का संरक्षण तथा सनातन संस्कृति का प्रचार-प्रसार है। अखाड़े में संन्यासियों को शास्त्र एवं शस्त्र दोनों की शिक्षा प्रदान की जाती रही है, जिससे वे समाज तथा धर्म की रक्षा के लिए सदैव तत्पर रहें।",
    "history_14": "गुरु-शिष्य परंपरा",
    "history_15": "निरंजनी अखाड़े की पहचान उसकी अखंड गुरु-शिष्य परंपरा है। प्रत्येक संन्यासी अपने गुरु से दीक्षा प्राप्त कर वैदिक ज्ञान, योग, तप, संयम तथा सेवा के मार्ग पर अग्रसर होता है। यह परंपरा आज भी उसी श्रद्धा एवं अनुशासन के साथ निरंतर आगे बढ़ रही है।",
    "history_16": "कुंभ पर्व में निरंजनी अखाड़ा",
    "history_17": "महाकुंभ एवं अर्धकुंभ में निरंजनी अखाड़े का शाही स्नान अत्यंत महत्वपूर्ण माना जाता है। लाखों श्रद्धालु अखाड़े के नागा संन्यासियों एवं संतों के दिव्य दर्शन हेतु उपस्थित होते हैं। यह केवल धार्मिक आयोजन नहीं बल्कि सनातन संस्कृति की महान परंपरा का उत्सव है।",
    "history_18": "आध्यात्मिक विरासत",
    "history_19": "निरंजनी अखाड़ा वेद, उपनिषद, पुराण, योग, ध्यान, तपस्या एवं भारतीय आध्यात्मिक संस्कृति की अमूल्य धरोहर को संरक्षित करने का कार्य करता है। इसके आश्रम एवं मढ़ियाँ देशभर में धर्म, शिक्षा, सेवा एवं साधना के केंद्र के रूप में कार्यरत हैं।",
    "history_20": "आज श्री पंचायती अखाड़ा श्री निरंजनी आधुनिक युग में भी अपनी प्राचीन परंपराओं को अक्षुण्ण रखते हुए धर्म, संस्कृति, शिक्षा, सेवा एवं आध्यात्मिक जागरण के कार्यों में सक्रिय है। देशभर में स्थित इसकी शाखाएँ, मढ़ियाँ एवं संत समाज सनातन धर्म के प्रचार-प्रसार में निरंतर योगदान दे रहे हैं।",
    "history_21": "इतिहास की प्रमुख विशेषताएँ",
    "history_22": "निरंजनी अखाड़े की शक्ति इसकी अखंड गुरु-शिष्य परंपरा में निहित है, जहाँ आध्यात्मिक ज्ञान, अनुशासन एवं सन्यास संस्कार पीढ़ी-दर-पीढ़ी हस्तांतरित होते हैं।",
    "history_23": "धर्म संरक्षण",
    "history_24": "अखाड़े का प्रमुख उद्देश्य सनातन धर्म, वैदिक संस्कृति एवं भारतीय आध्यात्मिक विरासत का संरक्षण तथा समाज में धर्म जागरण करना है।",
    "history_25": "श्री पंचायती अखाड़ा श्री निरंजनी केवल एक संन्यासी संगठन नहीं, बल्कि सनातन धर्म, वैदिक परंपरा, आध्यात्मिक साधना तथा राष्ट्रधर्म की रक्षा का एक जीवंत केंद्र है। इसकी परंपराएँ सदियों से गुरु-शिष्य संबंध, तप, त्याग, सेवा एवं धर्म संरक्षण के आदर्शों पर आधारित हैं।",
    "history_26": "निरंजनी अखाड़े की विशेषताएँ",
    "history_27": "श्री पंचायती अखाड़ा श्री निरंजनी भारतीय सनातन परंपरा के उन महान आध्यात्मिक संस्थानों में से एक है जिसने धर्म, साधना एवं संस्कृति के संरक्षण में अमूल्य योगदान दिया है।",
    "history_28": "दशनामी संन्यास परंपरा",
    "history_29": "आदि शंकराचार्य द्वारा स्थापित दशनामी संन्यास परंपरा के सिद्धांतों का पालन करते हुए अखाड़ा वैदिक ज्ञान एवं आध्यात्मिक अनुशासन का संवाहक है।",
    "history_30": "कुंभ की गौरवशाली परंपरा",
    "history_31": "महाकुंभ एवं अर्धकुंभ में निरंजनी अखाड़े की शाही पेशवाई और शाही स्नान इसकी प्राचीन परंपरा एवं आध्यात्मिक गौरव का प्रतीक हैं।"
}
};

let currentLang = localStorage.getItem('language') || 'hi';

function updateContent() {
    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[currentLang] && translations[currentLang][key]) {
            el.innerHTML = translations[currentLang][key];
        }
    });
}

function setLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('language', lang);
    updateContent();
}

function toggleLanguage() {
    if (currentLang === 'hi') {
        setLanguage('en');
    } else {
        setLanguage('hi');
    }
}

document.addEventListener('DOMContentLoaded', () => {
    updateContent();
});
